package personal.project;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author titus
 */
public class inventory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inventory.class.getName());
    private java.util.List<Object[]> inventoryList = new java.util.ArrayList<>();
    private int currentIndex = -1;
    /**
     * Creates new form inventory
     */
    private void loadInventory() {
    inventoryList.clear();
    String sql = "SELECT INVENTORY_ID, ITEM_NAME, QUANTITY, UNIT, REORDER_LEVEL, SUPPLIER_ID FROM inventory";

    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
         java.sql.ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            inventoryList.add(new Object[]{
                rs.getInt("INVENTORY_ID"),
                rs.getString("ITEM_NAME"),
                rs.getInt("QUANTITY"),
                rs.getString("UNIT"),
                rs.getObject("REORDER_LEVEL"),
                rs.getObject("SUPPLIER_ID")
            });
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

private void showRecord(int index) {
    if (inventoryList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No records found.");
        return;
    }
    if (index < 0) index = 0;
    if (index >= inventoryList.size()) index = inventoryList.size() - 1;
    currentIndex = index;

    Object[] record = inventoryList.get(currentIndex);
    txtInventoryID.setText(String.valueOf(record[0]));
    txtItemName.setText((String) record[1]);
    txtQuantity.setText(String.valueOf(record[2]));
    txtUnit.setText(record[3] == null ? "" : (String) record[3]);
    txtReorderLevel.setText(record[4] == null ? "" : String.valueOf(record[4]));
    txtSupplierID.setText(record[5] == null ? "" : String.valueOf(record[5]));
}

private void clearFields() {
    txtInventoryID.setText("");
    txtItemName.setText("");
    txtQuantity.setText("");
    txtUnit.setText("");
    txtReorderLevel.setText("");
    txtSupplierID.setText("");
}
    public inventory() {
    setLocationRelativeTo(null);
    setTitle("INVENTORY");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        btnPrevious = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtInventoryID = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtReorderLevel = new javax.swing.JTextField();
        txtSupplierID = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(this::btnPreviousActionPerformed);

        btnSave.setText("SAVE");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnFind.setText("FIND");
        btnFind.addActionListener(this::btnFindActionPerformed);

        btnFirst.setText("FIRST");
        btnFirst.addActionListener(this::btnFirstActionPerformed);

        btnLast.setText("LAST");
        btnLast.addActionListener(this::btnLastActionPerformed);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnNext.setText("NEXT");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnExit.setText("EXIT");
        btnExit.addActionListener(this::btnExitActionPerformed);

        jLabel1.setText("INVENTORY_ID");

        jLabel2.setText("ITEM_NAME");

        jLabel3.setText("QUANTITY");

        jLabel4.setText("UNIT");

        jLabel5.setText("REORDER_LEVEL");

        jLabel6.setText("SUPPLIER_ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFind)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExit))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFirst)
                                .addGap(18, 18, 18)
                                .addComponent(btnLast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInventoryID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInventoryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtReorderLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnFirst)
                    .addComponent(btnLast)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnFind)
                    .addComponent(btnDelete)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (inventoryList.isEmpty()) {
            loadInventory();
        }
        showRecord(currentIndex - 1);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
 
    String itemName = txtItemName.getText().trim();
    String quantityStr = txtQuantity.getText().trim();
    String unit = txtUnit.getText().trim();
    String reorderStr = txtReorderLevel.getText().trim();
    String supplierStr = txtSupplierID.getText().trim();

    if (itemName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Item Name");
        txtItemName.requestFocus();
        return;
    }
    if (quantityStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Quantity");
        txtQuantity.requestFocus();
        return;
    }

    int quantity;
    Integer reorderLevel = null;
    Integer supplierId = null;
    try {
        quantity = Integer.parseInt(quantityStr);
        if (!reorderStr.isEmpty()) {
            reorderLevel = Integer.parseInt(reorderStr);
        }
        if (!supplierStr.isEmpty()) {
            supplierId = Integer.parseInt(supplierStr);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Quantity, Reorder Level, and Supplier ID must be numbers.");
        return;
    }

    String sql = "INSERT INTO inventory (ITEM_NAME, QUANTITY, UNIT, REORDER_LEVEL, SUPPLIER_ID) VALUES (?, ?, ?, ?, ?)";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setString(1, itemName);
        stmt.setInt(2, quantity);
        stmt.setString(3, unit.isEmpty() ? null : unit);
        if (reorderLevel == null) stmt.setNull(4, java.sql.Types.INTEGER); else stmt.setInt(4, reorderLevel);
        if (supplierId == null) stmt.setNull(5, java.sql.Types.INTEGER); else stmt.setInt(5, supplierId);
        stmt.executeUpdate();

        JOptionPane.showMessageDialog(this, "Item saved successfully!");
        clearFields();
        loadInventory();
        currentIndex = -1;

    } catch (java.sql.SQLIntegrityConstraintViolationException e) {
        JOptionPane.showMessageDialog(this,
            "Supplier ID doesn't exist in the suppliers table.",
            "Save Blocked", JOptionPane.WARNING_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
 
    String idStr = txtInventoryID.getText().trim();
    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter an Inventory ID to search");
        txtInventoryID.requestFocus();
        return;
    }

    int inventoryId;
    try {
        inventoryId = Integer.parseInt(idStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Inventory ID must be a number.");
        return;
    }

    String sql = "SELECT INVENTORY_ID, ITEM_NAME, QUANTITY, UNIT, REORDER_LEVEL, SUPPLIER_ID FROM inventory WHERE INVENTORY_ID = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setInt(1, inventoryId);
        try (java.sql.ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                txtInventoryID.setText(String.valueOf(rs.getInt("INVENTORY_ID")));
                txtItemName.setText(rs.getString("ITEM_NAME"));
                txtQuantity.setText(String.valueOf(rs.getInt("QUANTITY")));
                txtUnit.setText(rs.getString("UNIT") == null ? "" : rs.getString("UNIT"));
                Object reorder = rs.getObject("REORDER_LEVEL");
                txtReorderLevel.setText(reorder == null ? "" : String.valueOf(reorder));
                Object supplier = rs.getObject("SUPPLIER_ID");
                txtSupplierID.setText(supplier == null ? "" : String.valueOf(supplier));
            } else {
                JOptionPane.showMessageDialog(this, "No item found with that Inventory ID.");
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnFindActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        loadInventory();
        showRecord(0);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        loadInventory();
        showRecord(inventoryList.size() - 1);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    String idStr = txtInventoryID.getText().trim();

    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Inventory ID to delete");
        txtInventoryID.requestFocus();
        return;
    }

    int inventoryId;
    try {
        inventoryId = Integer.parseInt(idStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Inventory ID must be a number.");
        return;
    }

    String checkSql = "SELECT COUNT(*) FROM inventory WHERE INVENTORY_ID = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {

        checkStmt.setInt(1, inventoryId);
        try (java.sql.ResultSet rs = checkStmt.executeQuery()) {
            rs.next();
            if (rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(this, "No item found with that Inventory ID.");
                return;
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this item?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String deleteSql = "DELETE FROM inventory WHERE INVENTORY_ID = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement deleteStmt = conn.prepareStatement(deleteSql)) {

        deleteStmt.setInt(1, inventoryId);
        int rows = deleteStmt.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Deleted successfully!");
            clearFields();
            loadInventory();
            currentIndex = -1;
        } else {
            JOptionPane.showMessageDialog(this, "No matching record found.");
        }

    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (inventoryList.isEmpty()) {
            loadInventory();
        }
        showRecord(currentIndex + 1);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to Exit?","Confirm Exit",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inventory().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtInventoryID;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtReorderLevel;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
