package personal.project;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author titus
 */

public class LOG_IN extends javax.swing.JFrame {
private int failedAttempts = 0;
private static final int MAX_ATTEMPTS = 3;
private boolean loginLocked = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LOG_IN.class.getName());

    /**
     * Creates new form LOG_IN
     */
    public LOG_IN() {
        setLocationRelativeTo(null);
        setTitle("LOG IN");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlogin = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        lblpassword = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        btnforgotpassword = new javax.swing.JButton();
        chkShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnlogin.setText("LOG IN");
        btnlogin.addActionListener(this::btnloginActionPerformed);

        btncancel.setText("CANCEL");
        btncancel.addActionListener(this::btncancelActionPerformed);

        lblpassword.setText("PASSWORD");

        lblusername.setText("USERNAME");

        txtusername.addActionListener(this::txtusernameActionPerformed);

        btnforgotpassword.setText("FORGOT PASSWORD");
        btnforgotpassword.addActionListener(this::btnforgotpasswordActionPerformed);

        chkShowPassword.setText("SHOW PASSWORD");
        chkShowPassword.addActionListener(this::chkShowPasswordActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblusername)
                            .addComponent(lblpassword)
                            .addComponent(btnlogin))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncancel))
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnforgotpassword)
                        .addGap(37, 37, 37)
                        .addComponent(chkShowPassword)
                        .addGap(63, 63, 63))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblpassword)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(btnlogin))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnforgotpassword)
                    .addComponent(chkShowPassword))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed


    if (loginLocked) {
        JOptionPane.showMessageDialog(this, "Too many failed attempts. Please wait before trying again.");
        return;
    }

    String name = txtusername.getText().trim();
    String password = new String(txtpassword.getPassword()).trim();

    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter username");
        txtusername.requestFocus();
        return;
    }
    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter password");
        txtpassword.requestFocus();
        return;
    }

    String sql = "SELECT * FROM users WHERE username = ? AND password = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setString(1, name);
        stmt.setString(2, password);

        try (java.sql.ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                // Save username for next time
                java.util.prefs.Preferences prefs = java.util.prefs.Preferences.userNodeForPackage(LOG_IN.class);
                prefs.put("lastUsername", name);

                failedAttempts = 0;
                new MENU().Main();
                this.dispose();
            } else {
                failedAttempts++;
                int remaining = MAX_ATTEMPTS - failedAttempts;

                if (remaining <= 0) {
                    loginLocked = true;
                    JOptionPane.showMessageDialog(this, "Too many failed attempts. Login locked for 30 seconds.");
                    btnlogin.setEnabled(false);

                    javax.swing.Timer timer = new javax.swing.Timer(30000, e -> {
                        loginLocked = false;
                        failedAttempts = 0;
                        btnlogin.setEnabled(true);
                        JOptionPane.showMessageDialog(this, "You can try logging in again.");
                    });
                    timer.setRepeats(false);
                    timer.start();
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid username or password. " + remaining + " attempt(s) remaining.");
                }

                txtpassword.setText("");
                txtpassword.requestFocus();
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }


    }//GEN-LAST:event_btnloginActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirm Exit", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btncancelActionPerformed

    private void txtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusernameActionPerformed
      txtusername.addActionListener(this::txtusernameActionPerformed); 
      txtpassword.addActionListener(this::txtpasswordActionPerformed);// TODO add your handling code here:
    }//GEN-LAST:event_txtusernameActionPerformed

    private void btnforgotpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforgotpasswordActionPerformed

    String name = JOptionPane.showInputDialog(this, "Enter your username:");
    if (name == null || name.trim().isEmpty()) {
        return;
    }
    name = name.trim();

    String checkSql = "SELECT COUNT(*) FROM users WHERE username = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {

        checkStmt.setString(1, name);
        try (java.sql.ResultSet rs = checkStmt.executeQuery()) {
            rs.next();
            if (rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(this, "No account found with that username.");
                return;
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        return;
    }

    String newPassword = JOptionPane.showInputDialog(this, "Enter a new password:");
    if (newPassword == null || newPassword.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Password reset cancelled.");
        return;
    }

    String updateSql = "UPDATE users SET password = ? WHERE username = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement updateStmt = conn.prepareStatement(updateSql)) {

        updateStmt.setString(1, newPassword.trim());
        updateStmt.setString(2, name);
        updateStmt.executeUpdate();

        JOptionPane.showMessageDialog(this, "Password updated successfully. You can now log in.");
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnforgotpasswordActionPerformed

    private void chkShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowPasswordActionPerformed

    if (chkShowPassword.isSelected()) {
        txtpassword.setEchoChar((char) 0);
    } else {
        txtpassword.setEchoChar('•');
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_chkShowPasswordActionPerformed
private void txtpasswordActionPerformed(java.awt.event.ActionEvent evt) {
    btnloginActionPerformed(evt);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LOG_IN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnforgotpassword;
    private javax.swing.JButton btnlogin;
    private javax.swing.JCheckBox chkShowPassword;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
