package personal.project;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author titus
 */
public class maintenance_requests extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(maintenance_requests.class.getName());
    private java.util.List<Object[]> maintenanceList = new java.util.ArrayList<>();
    private int currentIndex = -1;
    /**
     * Creates new form maintenance_requests
     */
    private void loadMaintenance() {
    maintenanceList.clear();
    String sql = "SELECT maintenance_id, room_id, staff_id, issue_description, reported_date, request_status, resolved_date FROM maintenance_requests";

    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
         java.sql.ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            maintenanceList.add(new Object[]{
                rs.getInt("maintenance_id"),
                rs.getInt("room_id"),
                rs.getInt("staff_id"),
                rs.getString("issue_description"),
                rs.getDate("reported_date"),
                rs.getString("request_status"),
                rs.getDate("resolved_date")
            });
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

private void showRecord(int index) {
    if (maintenanceList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No records found.");
        return;
    }
    if (index < 0) index = 0;
    if (index >= maintenanceList.size()) index = maintenanceList.size() - 1;
    currentIndex = index;

    Object[] record = maintenanceList.get(currentIndex);
    txtMaintenanceID.setText(String.valueOf(record[0]));
    txtRoomID.setText(String.valueOf(record[1]));
    txtStaffID.setText(String.valueOf(record[2]));
    txtIssueDescription.setText((String) record[3]);
    txtReportedDate.setText(String.valueOf(record[4]));
    txtRequestedStatus.setText((String) record[5]);
    txtResolvedDate.setText(record[6] == null ? "" : String.valueOf(record[6]));
}

private void clearFields() {
    txtMaintenanceID.setText("");
    txtRoomID.setText("");
    txtStaffID.setText("");
    txtIssueDescription.setText("");
    txtReportedDate.setText("");
    txtRequestedStatus.setText("");
    txtResolvedDate.setText("");
}
    public maintenance_requests() {
        setLocationRelativeTo(null);
        setTitle("MAINTENANCE REQUESTS");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaintenanceID = new javax.swing.JTextField();
        txtRoomID = new javax.swing.JTextField();
        txtStaffID = new javax.swing.JTextField();
        txtIssueDescription = new javax.swing.JTextField();
        txtReportedDate = new javax.swing.JTextField();
        txtRequestedStatus = new javax.swing.JTextField();
        txtResolvedDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSave.setText("SAVE");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(this::btnPreviousActionPerformed);

        btnFirst.setText("FIRST");
        btnFirst.addActionListener(this::btnFirstActionPerformed);

        btnFind.setText("FIND");
        btnFind.addActionListener(this::btnFindActionPerformed);

        btnLast.setText("LAST");
        btnLast.addActionListener(this::btnLastActionPerformed);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnNext.setText("NEXT");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnExit.setText("EXIT");
        btnExit.addActionListener(this::btnExitActionPerformed);

        jLabel1.setText("MAINTENANCE_ID");

        jLabel2.setText("ROOM_ID");

        jLabel3.setText("STAFF_ID");

        jLabel4.setText("ISSUE_DESCRIPTION");

        jLabel5.setText("REPORTED_DATE");

        jLabel6.setText("REQUESTED_STATUS");

        jLabel7.setText("RESOLVED_DATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnFirst)
                                .addGap(18, 18, 18)
                                .addComponent(btnLast)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFind)
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExit)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtReportedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtResolvedDate, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRequestedStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(52, 52, 52)
                                    .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMaintenanceID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(txtIssueDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtMaintenanceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReportedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtRequestedStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtResolvedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStaffID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIssueDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnFirst)
                    .addComponent(btnLast)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnFind)
                    .addComponent(btnDelete)
                    .addComponent(btnExit)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
      
    String roomIdStr = txtRoomID.getText().trim();
    String staffIdStr = txtStaffID.getText().trim();
    String issueDescription = txtIssueDescription.getText().trim();
    String reportedDateStr = txtReportedDate.getText().trim();
    String status = txtRequestedStatus.getText().trim();
    String resolvedDateStr = txtResolvedDate.getText().trim();

    if (roomIdStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Room ID");
        txtRoomID.requestFocus();
        return;
    }
    if (staffIdStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Staff ID");
        txtStaffID.requestFocus();
        return;
    }
    if (issueDescription.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Issue Description");
        txtIssueDescription.requestFocus();
        return;
    }
    if (reportedDateStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Reported Date (YYYY-MM-DD)");
        txtReportedDate.requestFocus();
        return;
    }
    if (status.isEmpty()) {
        status = "Open"; // matches database default
    }

    int roomId, staffId;
    java.sql.Date reportedDate;
    java.sql.Date resolvedDate = null;
    try {
        roomId = Integer.parseInt(roomIdStr);
        staffId = Integer.parseInt(staffIdStr);
        reportedDate = java.sql.Date.valueOf(reportedDateStr);
        if (!resolvedDateStr.isEmpty()) {
            resolvedDate = java.sql.Date.valueOf(resolvedDateStr);
        }
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Room ID and Staff ID must be numbers; dates must be YYYY-MM-DD.");
        return;
    }

    String sql = "INSERT INTO maintenance_requests (room_id, staff_id, issue_description, reported_date, request_status, resolved_date) VALUES (?, ?, ?, ?, ?, ?)";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setInt(1, roomId);
        stmt.setInt(2, staffId);
        stmt.setString(3, issueDescription);
        stmt.setDate(4, reportedDate);
        stmt.setString(5, status);
        if (resolvedDate == null) stmt.setNull(6, java.sql.Types.DATE); else stmt.setDate(6, resolvedDate);
        stmt.executeUpdate();

        JOptionPane.showMessageDialog(this, "Maintenance request saved successfully!");
        clearFields();
        loadMaintenance();
        currentIndex = -1;

    } catch (java.sql.SQLIntegrityConstraintViolationException e) {
        JOptionPane.showMessageDialog(this,
            "Room ID or Staff ID doesn't exist in their tables.",
            "Save Blocked", JOptionPane.WARNING_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (maintenanceList.isEmpty()) {
            loadMaintenance();
        }
        showRecord(currentIndex - 1);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        loadMaintenance();
        showRecord(0);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
    
    String idStr = txtMaintenanceID.getText().trim();
    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter a Maintenance ID to search");
        txtMaintenanceID.requestFocus();
        return;
    }

    int maintenanceId;
    try {
        maintenanceId = Integer.parseInt(idStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Maintenance ID must be a number.");
        return;
    }

    String sql = "SELECT maintenance_id, room_id, staff_id, issue_description, reported_date, request_status, resolved_date FROM maintenance_requests WHERE maintenance_id = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setInt(1, maintenanceId);
        try (java.sql.ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                txtMaintenanceID.setText(String.valueOf(rs.getInt("maintenance_id")));
                txtRoomID.setText(String.valueOf(rs.getInt("room_id")));
                txtStaffID.setText(String.valueOf(rs.getInt("staff_id")));
                txtIssueDescription.setText(rs.getString("issue_description"));
                txtReportedDate.setText(String.valueOf(rs.getDate("reported_date")));
                txtRequestedStatus.setText(rs.getString("request_status"));
                java.sql.Date resolved = rs.getDate("resolved_date");
                txtResolvedDate.setText(resolved == null ? "" : String.valueOf(resolved));
            } else {
                JOptionPane.showMessageDialog(this, "No maintenance request found with that ID.");
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnFindActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        loadMaintenance();
        showRecord(maintenanceList.size() - 1);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    String idStr = txtMaintenanceID.getText().trim();

    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Maintenance ID to delete");
        txtMaintenanceID.requestFocus();
        return;
    }

    int maintenanceId;
    try {
        maintenanceId = Integer.parseInt(idStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Maintenance ID must be a number.");
        return;
    }

    String checkSql = "SELECT COUNT(*) FROM maintenance_requests WHERE maintenance_id = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {

        checkStmt.setInt(1, maintenanceId);
        try (java.sql.ResultSet rs = checkStmt.executeQuery()) {
            rs.next();
            if (rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(this, "No maintenance request found with that ID.");
                return;
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this request?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String deleteSql = "DELETE FROM maintenance_requests WHERE maintenance_id = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement deleteStmt = conn.prepareStatement(deleteSql)) {

        deleteStmt.setInt(1, maintenanceId);
        int rows = deleteStmt.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Deleted successfully!");
            clearFields();
            loadMaintenance();
            currentIndex = -1;
        } else {
            JOptionPane.showMessageDialog(this, "No matching record found.");
        }

    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (maintenanceList.isEmpty()) {
            loadMaintenance();
        }
        showRecord(currentIndex + 1);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to Exit?","Confirm Exit",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
        this.dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new maintenance_requests().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtIssueDescription;
    private javax.swing.JTextField txtMaintenanceID;
    private javax.swing.JTextField txtReportedDate;
    private javax.swing.JTextField txtRequestedStatus;
    private javax.swing.JTextField txtResolvedDate;
    private javax.swing.JTextField txtRoomID;
    private javax.swing.JTextField txtStaffID;
    // End of variables declaration//GEN-END:variables
}
