package personal.project;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author titus
 */
public class reviews extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(reviews.class.getName());
    private java.util.List<Object[]> reviewsList = new java.util.ArrayList<>();
    private  int currentIndex = -1;
    /**
     * Creates new form reviews
     */
    private void loadReviews() {
    reviewsList.clear();
    String sql = "SELECT REVIEW_ID, GUEST_ID, ROOM_ID, RATING, COMMENT, REVIEW_DATE FROM reviews";

    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
         java.sql.ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            reviewsList.add(new Object[]{
                rs.getInt("REVIEW_ID"),
                rs.getInt("GUEST_ID"),
                rs.getInt("ROOM_ID"),
                rs.getInt("RATING"),
                rs.getString("COMMENT"),
                rs.getDate("REVIEW_DATE")
            });
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

private void showRecord(int index) {
    if (reviewsList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No records found.");
        return;
    }
    if (index < 0) index = 0;
    if (index >= reviewsList.size()) index = reviewsList.size() - 1;
    currentIndex = index;

    Object[] record = reviewsList.get(currentIndex);
    txtReviewID.setText(String.valueOf(record[0]));
    txtGuestID.setText(String.valueOf(record[1]));
    txtRoomID.setText(String.valueOf(record[2]));
    txtRating.setText(String.valueOf(record[3]));
    txtComment.setText(record[4] == null ? "" : (String) record[4]);
    txtReviewDate.setText(String.valueOf(record[5]));
}

private void clearFields() {
    txtReviewID.setText("");
    txtGuestID.setText("");
    txtRoomID.setText("");
    txtRating.setText("");
    txtComment.setText("");
    txtReviewDate.setText("");
}
    public reviews() {
        setLocationRelativeTo(null);
        setTitle("REVIEWS");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtReviewID = new javax.swing.JTextField();
        txtGuestID = new javax.swing.JTextField();
        txtRoomID = new javax.swing.JTextField();
        txtRating = new javax.swing.JTextField();
        txtComment = new javax.swing.JTextField();
        txtReviewDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSave.setText("SAVE");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(this::btnPreviousActionPerformed);

        btnFirst.setText("FIRST");
        btnFirst.addActionListener(this::btnFirstActionPerformed);

        btnFind.setText("FIND");
        btnFind.addActionListener(this::btnFindActionPerformed);

        btnLast.setText("LAST");
        btnLast.addActionListener(this::btnLastActionPerformed);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnNext.setText("NEXT");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnExit.setText("EXIT");
        btnExit.addActionListener(this::btnExitActionPerformed);

        jLabel1.setText("REVIEW_ID");

        jLabel2.setText("GUEST_ID");

        jLabel3.setText("ROOM_ID");

        jLabel4.setText("RATING");

        jLabel5.setText("COMMENT");

        jLabel6.setText("REVIEW_DATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFirst))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrevious)
                                .addGap(35, 35, 35)
                                .addComponent(btnFind)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(51, 51, 51)
                                .addComponent(btnExit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLast)
                                .addGap(38, 38, 38)
                                .addComponent(btnNext))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtGuestID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(txtReviewID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel6)))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReviewDate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(txtReviewID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtGuestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtRoomID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReviewDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnFirst)
                    .addComponent(btnLast)
                    .addComponent(btnNext))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnFind)
                    .addComponent(btnDelete)
                    .addComponent(btnExit))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    String guestIdStr = txtGuestID.getText().trim();
    String roomIdStr = txtRoomID.getText().trim();
    String ratingStr = txtRating.getText().trim();
    String comment = txtComment.getText().trim();
    String reviewDateStr = txtReviewDate.getText().trim();

    if (guestIdStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Guest ID");
        txtGuestID.requestFocus();
        return;
    }
    if (roomIdStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Room ID");
        txtRoomID.requestFocus();
        return;
    }
    if (ratingStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Rating");
        txtRating.requestFocus();
        return;
    }
    if (reviewDateStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Review Date (YYYY-MM-DD)");
        txtReviewDate.requestFocus();
        return;
    }

    int guestId, roomId, rating;
    java.sql.Date reviewDate;
    try {
        guestId = Integer.parseInt(guestIdStr);
        roomId = Integer.parseInt(roomIdStr);
        rating = Integer.parseInt(ratingStr);
        reviewDate = java.sql.Date.valueOf(reviewDateStr);
    } catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, "Guest ID, Room ID, and Rating must be numbers; Date must be YYYY-MM-DD.");
        return;
    }

    String sql = "INSERT INTO reviews (GUEST_ID, ROOM_ID, RATING, COMMENT, REVIEW_DATE) VALUES (?, ?, ?, ?, ?)";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setInt(1, guestId);
        stmt.setInt(2, roomId);
        stmt.setInt(3, rating);
        stmt.setString(4, comment.isEmpty() ? null : comment);
        stmt.setDate(5, reviewDate);
        stmt.executeUpdate();

        JOptionPane.showMessageDialog(this, "Review saved successfully!");
        clearFields();
        loadReviews();
        currentIndex = -1;

    } catch (java.sql.SQLIntegrityConstraintViolationException e) {
        JOptionPane.showMessageDialog(this,
            "Guest ID or Room ID doesn't exist in their tables.",
            "Save Blocked", JOptionPane.WARNING_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (reviewsList.isEmpty()) {
            loadReviews();
        }
        showRecord(currentIndex - 1);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        loadReviews();
        showRecord(0);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
    
    String idStr = txtReviewID.getText().trim();
    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter a Review ID to search");
        txtReviewID.requestFocus();
        return;
    }

    int reviewId;
    try {
        reviewId = Integer.parseInt(idStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Review ID must be a number.");
        return;
    }

    String sql = "SELECT REVIEW_ID, GUEST_ID, ROOM_ID, RATING, COMMENT, REVIEW_DATE FROM reviews WHERE REVIEW_ID = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setInt(1, reviewId);
        try (java.sql.ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                txtReviewID.setText(String.valueOf(rs.getInt("REVIEW_ID")));
                txtGuestID.setText(String.valueOf(rs.getInt("GUEST_ID")));
                txtRoomID.setText(String.valueOf(rs.getInt("ROOM_ID")));
                txtRating.setText(String.valueOf(rs.getInt("RATING")));
                txtComment.setText(rs.getString("COMMENT") == null ? "" : rs.getString("COMMENT"));
                txtReviewDate.setText(String.valueOf(rs.getDate("REVIEW_DATE")));
            } else {
                JOptionPane.showMessageDialog(this, "No review found with that Review ID.");
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnFindActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        loadReviews();
        showRecord(reviewsList.size() - 1);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    String idStr = txtReviewID.getText().trim();

    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Review ID to delete");
        txtReviewID.requestFocus();
        return;
    }

    int reviewId;
    try {
        reviewId = Integer.parseInt(idStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Review ID must be a number.");
        return;
    }

    String checkSql = "SELECT COUNT(*) FROM reviews WHERE REVIEW_ID = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {

        checkStmt.setInt(1, reviewId);
        try (java.sql.ResultSet rs = checkStmt.executeQuery()) {
            rs.next();
            if (rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(this, "No review found with that Review ID.");
                return;
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this review?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String deleteSql = "DELETE FROM reviews WHERE REVIEW_ID = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement deleteStmt = conn.prepareStatement(deleteSql)) {

        deleteStmt.setInt(1, reviewId);
        int rows = deleteStmt.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Deleted successfully!");
            clearFields();
            loadReviews();
            currentIndex = -1;
        } else {
            JOptionPane.showMessageDialog(this, "No matching record found.");
        }

    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (reviewsList.isEmpty()) {
            loadReviews();
        }
        showRecord(currentIndex + 1);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to Exit?","Confirm Exit",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
        this.dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new reviews().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtComment;
    private javax.swing.JTextField txtGuestID;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtReviewDate;
    private javax.swing.JTextField txtReviewID;
    private javax.swing.JTextField txtRoomID;
    // End of variables declaration//GEN-END:variables
}
