package personal.project;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author titus
 */
public class room_types extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(room_types.class.getName());
    private java.util.List<Object[]> roomTypesList = new java.util.ArrayList<>();
    private int currentIndex = -1;
    /**
     * Creates new form room_types
     */
    private void loadRoomTypes() {
    roomTypesList.clear();
    String sql = "SELECT room_type_id, type_name, base_price, capacity FROM room_types";

    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql);
         java.sql.ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            roomTypesList.add(new Object[]{
                rs.getInt("room_type_id"),
                rs.getString("type_name"),
                rs.getBigDecimal("base_price"),
                rs.getInt("capacity")
            });
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}

private void showRecord(int index) {
    if (roomTypesList.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No records found.");
        return;
    }
    if (index < 0) index = 0;
    if (index >= roomTypesList.size()) index = roomTypesList.size() - 1;
    currentIndex = index;

    Object[] record = roomTypesList.get(currentIndex);
    txtRoomTypeID.setText(String.valueOf(record[0]));
    txtTypeName.setText((String) record[1]);
    txtBasePrice.setText(String.valueOf(record[2]));
    txtCapacity.setText(String.valueOf(record[3]));
}

private void clearFields() {
    txtRoomTypeID.setText("");
    txtTypeName.setText("");
    txtBasePrice.setText("");
    txtCapacity.setText("");
}
    public room_types() {
        setLocationRelativeTo(null);
        setTitle("ROOM TYPES");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRoomTypeID = new javax.swing.JTextField();
        txtTypeName = new javax.swing.JTextField();
        txtBasePrice = new javax.swing.JTextField();
        txtCapacity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSave.setText("SAVE");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(this::btnPreviousActionPerformed);

        btnFirst.setText("FIRST");
        btnFirst.addActionListener(this::btnFirstActionPerformed);

        btnFind.setText("FIND");
        btnFind.addActionListener(this::btnFindActionPerformed);

        btnLast.setText("LAST");
        btnLast.addActionListener(this::btnLastActionPerformed);

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnNext.setText("NEXT");
        btnNext.addActionListener(this::btnNextActionPerformed);

        btnExit.setText("EXIT");
        btnExit.addActionListener(this::btnExitActionPerformed);

        jLabel1.setText("ROOM TYPE ID");

        jLabel2.setText("TYPE NAME");

        jLabel3.setText("BASE PRICE");

        jLabel4.setText("CAPACITY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrevious)
                                .addGap(35, 35, 35)
                                .addComponent(btnFind))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFirst)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(51, 51, 51)
                                .addComponent(btnExit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLast)
                                .addGap(38, 38, 38)
                                .addComponent(btnNext))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTypeName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(txtRoomTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtRoomTypeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtTypeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnFirst)
                    .addComponent(btnLast)
                    .addComponent(btnNext))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevious)
                    .addComponent(btnFind)
                    .addComponent(btnDelete)
                    .addComponent(btnExit))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
   
    String typeName = txtTypeName.getText().trim();
    String basePriceStr = txtBasePrice.getText().trim();
    String capacityStr = txtCapacity.getText().trim();

    if (typeName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Type Name");
        txtTypeName.requestFocus();
        return;
    }
    if (basePriceStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Base Price");
        txtBasePrice.requestFocus();
        return;
    }
    if (capacityStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Capacity");
        txtCapacity.requestFocus();
        return;
    }

    java.math.BigDecimal basePrice;
    int capacity;
    try {
        basePrice = new java.math.BigDecimal(basePriceStr);
        capacity = Integer.parseInt(capacityStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Base Price and Capacity must be numbers.");
        return;
    }

    String sql = "INSERT INTO room_types (type_name, base_price, capacity) VALUES (?, ?, ?)";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setString(1, typeName);
        stmt.setBigDecimal(2, basePrice);
        stmt.setInt(3, capacity);
        stmt.executeUpdate();

        JOptionPane.showMessageDialog(this, "Room type saved successfully!");
        clearFields();
        loadRoomTypes();
        currentIndex = -1;

    } catch (java.sql.SQLIntegrityConstraintViolationException e) {
        JOptionPane.showMessageDialog(this,
            "That type name already exists.",
            "Save Blocked", JOptionPane.WARNING_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        if (roomTypesList.isEmpty()) {
            loadRoomTypes();
        }
        showRecord(currentIndex - 1);
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        loadRoomTypes();
        showRecord(0);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
   
    String idStr = txtRoomTypeID.getText().trim();
    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter a Room Type ID to search");
        txtRoomTypeID.requestFocus();
        return;
    }

    int roomTypeId;
    try {
        roomTypeId = Integer.parseInt(idStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Room Type ID must be a number.");
        return;
    }

    String sql = "SELECT room_type_id, type_name, base_price, capacity FROM room_types WHERE room_type_id = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {

        stmt.setInt(1, roomTypeId);
        try (java.sql.ResultSet rs = stmt.executeQuery()) {
            if (rs.next()) {
                txtRoomTypeID.setText(String.valueOf(rs.getInt("room_type_id")));
                txtTypeName.setText(rs.getString("type_name"));
                txtBasePrice.setText(String.valueOf(rs.getBigDecimal("base_price")));
                txtCapacity.setText(String.valueOf(rs.getInt("capacity")));
            } else {
                JOptionPane.showMessageDialog(this, "No room type found with that ID.");
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnFindActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        loadRoomTypes();
        showRecord(roomTypesList.size() - 1);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    String idStr = txtRoomTypeID.getText().trim();

    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter the Room Type ID to delete");
        txtRoomTypeID.requestFocus();
        return;
    }

    int roomTypeId;
    try {
        roomTypeId = Integer.parseInt(idStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Room Type ID must be a number.");
        return;
    }

    String checkSql = "SELECT COUNT(*) FROM room_types WHERE room_type_id = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement checkStmt = conn.prepareStatement(checkSql)) {

        checkStmt.setInt(1, roomTypeId);
        try (java.sql.ResultSet rs = checkStmt.executeQuery()) {
            rs.next();
            if (rs.getInt(1) == 0) {
                JOptionPane.showMessageDialog(this, "No room type found with that ID.");
                return;
            }
        }
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this room type?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    String deleteSql = "DELETE FROM room_types WHERE room_type_id = ?";
    try (java.sql.Connection conn = DatabaseConnection.getConnection();
         java.sql.PreparedStatement deleteStmt = conn.prepareStatement(deleteSql)) {

        deleteStmt.setInt(1, roomTypeId);
        int rows = deleteStmt.executeUpdate();

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Deleted successfully!");
            clearFields();
            loadRoomTypes();
            currentIndex = -1;
        } else {
            JOptionPane.showMessageDialog(this, "No matching record found.");
        }

    } catch (java.sql.SQLIntegrityConstraintViolationException e) {
        JOptionPane.showMessageDialog(this,
            "Cannot delete: rooms are still using this room type.",
            "Delete Blocked", JOptionPane.WARNING_MESSAGE);
    } catch (java.sql.SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (roomTypesList.isEmpty()) {
            loadRoomTypes();
        }
        showRecord(currentIndex + 1);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to Exit?","Confirm Exit",JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
        this.dispose();
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new room_types().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtBasePrice;
    private javax.swing.JTextField txtCapacity;
    private javax.swing.JTextField txtRoomTypeID;
    private javax.swing.JTextField txtTypeName;
    // End of variables declaration//GEN-END:variables
}
